/**
 * Les adresses du Roto-Control, gelees (2026-10-08, Mika : "Roto control :
 * des fois ca fonctionne, des fois ca ne fonctionne pas"). Avant, le CC d'un
 * controle etait sa place sur la page (rotoCc) : chaque nouvelle disposition
 * redonnait le meme canal et le meme CC a une autre cible (59 controles ont
 * change de sens entre deux versions publiees le 2026-10-07), et un Roto
 * encore charge d'un ancien setup pilotait autre chose que ce que dit son
 * ecran. Desormais :
 * - une ligne = une adresse : le setup, le canal, le CC, la cible ; les
 *   potards sur le canal du setup, les boutons sur le canal + 8 ;
 * - la liste ne fait que grandir : on ne change ni ne retire jamais une
 *   ligne. Un controle deplace sur une autre page garde son adresse ; un
 *   controle retire du setup garde la sienne (un ancien setup du Roto la
 *   pilote encore, et elle n'est jamais redonnee) ;
 * - une nouvelle cible prend une adresse libre (midi/roto.ts la donne, et
 *   la console du site en dev dit la ligne a ajouter ici, a la fin) ;
 * - la meme cible deux fois dans un setup (MASTER sur les deux pages des
 *   platines du DECK) : deux lignes, dans l'ordre des controles.
 * Graine : la table du site au 2026-10-08 (la meme qu'avant, controle par
 * controle : canal, CC et mode identiques), donc rien ne change d'adresse ;
 * seuls les noms des setups portent la version (midi/roto.ts).
 */

import type { RotoSetupName } from './roto';

/** setup, canal (1 a 16), CC (0 a 127), cible du site (midi/targets.ts, dj/midi.ts, bass/midi.ts) */
export type RotoKey = readonly [RotoSetupName, number, number, string];

export const ROTO_KEYS: readonly RotoKey[] = [
  // RYTM (setup 11), potards canal 1, page 1
  ['RYTM', 1, 14, 'rytm:enc:level'],
  ['RYTM', 1, 15, 'rytm:enc:tempo'],
  ['RYTM', 1, 16, 'rytm:enc:swing'],
  ['RYTM', 1, 17, 'rytm:enc:stretch'],
  ['RYTM', 1, 18, 'rytm:enc:dist'],
  ['RYTM', 1, 19, 'rytm:enc:chorus'],
  ['RYTM', 1, 20, 'rytm:enc:delay'],
  ['RYTM', 1, 21, 'rytm:enc:reverb'],
  // RYTM (setup 11), potards canal 1, page 2
  ['RYTM', 1, 22, 'rytm:enc:vol'],
  ['RYTM', 1, 23, 'rytm:enc:vsound'],
  ['RYTM', 1, 24, 'rytm:enc:tone'],
  ['RYTM', 1, 25, 'rytm:enc:vdecay'],
  ['RYTM', 1, 26, 'rytm:enc:vdist'],
  ['RYTM', 1, 27, 'rytm:enc:vchorus'],
  ['RYTM', 1, 28, 'rytm:enc:vdelay'],
  ['RYTM', 1, 29, 'rytm:enc:vreverb'],
  // RYTM (setup 11), potards canal 1, page 3
  ['RYTM', 1, 30, 'rytm:voice:BD:level'],
  ['RYTM', 1, 31, 'rytm:voice:SD:level'],
  ['RYTM', 1, 102, 'rytm:voice:CH:level'],
  ['RYTM', 1, 103, 'rytm:voice:OH:level'],
  ['RYTM', 1, 104, 'rytm:voice:CP:level'],
  ['RYTM', 1, 105, 'rytm:voice:TOM:level'],
  ['RYTM', 1, 106, 'rytm:voice:HT:level'],
  ['RYTM', 1, 107, 'rytm:voice:CY:level'],
  // RYTM (setup 11), potards canal 1, page 4
  ['RYTM', 1, 108, 'rytm:kit:bd'],
  ['RYTM', 1, 109, 'rytm:kit:tune'],
  ['RYTM', 1, 110, 'rytm:kit:attack'],
  ['RYTM', 1, 111, 'rytm:kit:decay'],
  ['RYTM', 1, 112, 'rytm:kit:drive'],
  ['RYTM', 1, 113, 'rytm:kit:sd'],
  ['RYTM', 1, 114, 'rytm:kit:snappy'],
  ['RYTM', 1, 115, 'rytm:kit:hh'],
  // RYTM (setup 11), boutons canal 9, page 1
  ['RYTM', 9, 14, 'rytm:running'],
  ['RYTM', 9, 15, 'rytm:random'],
  ['RYTM', 9, 16, 'rytm:clear'],
  ['RYTM', 9, 17, 'rytm:edit'],
  ['RYTM', 9, 18, 'rytm:open'],
  ['RYTM', 9, 19, 'nav:machines'],
  ['RYTM', 9, 20, 'nav:prev'],
  ['RYTM', 9, 21, 'nav:next'],
  // RYTM (setup 11), boutons canal 9, page 2
  ['RYTM', 9, 22, 'rytm:pad:BD'],
  ['RYTM', 9, 23, 'rytm:pad:SD'],
  ['RYTM', 9, 24, 'rytm:pad:CH'],
  ['RYTM', 9, 25, 'rytm:pad:OH'],
  ['RYTM', 9, 26, 'rytm:pad:CP'],
  ['RYTM', 9, 27, 'rytm:pad:TOM'],
  ['RYTM', 9, 28, 'rytm:pad:HT'],
  ['RYTM', 9, 29, 'rytm:pad:CY'],
  // RYTM (setup 11), boutons canal 9, page 3
  ['RYTM', 9, 30, 'rytm:voice:BD:mute'],
  ['RYTM', 9, 31, 'rytm:voice:SD:mute'],
  ['RYTM', 9, 102, 'rytm:voice:CH:mute'],
  ['RYTM', 9, 103, 'rytm:voice:OH:mute'],
  ['RYTM', 9, 104, 'rytm:voice:CP:mute'],
  ['RYTM', 9, 105, 'rytm:voice:TOM:mute'],
  ['RYTM', 9, 106, 'rytm:voice:HT:mute'],
  ['RYTM', 9, 107, 'rytm:voice:CY:mute'],
  // RYTM (setup 11), boutons canal 9, page 4
  ['RYTM', 9, 108, 'rytm:ptn:0'],
  ['RYTM', 9, 109, 'rytm:ptn:1'],
  ['RYTM', 9, 110, 'rytm:ptn:2'],
  ['RYTM', 9, 111, 'rytm:ptn:3'],
  ['RYTM', 9, 112, 'rytm:ptn:4'],
  ['RYTM', 9, 113, 'rytm:ptn:5'],
  ['RYTM', 9, 114, 'rytm:ptn:6'],
  ['RYTM', 9, 115, 'rytm:ptn:7'],
  // ARP (setup 12), potards canal 2, page 1
  ['ARP', 2, 14, 'voy:knob:rate'],
  ['ARP', 2, 15, 'voy:knob:mode'],
  ['ARP', 2, 16, 'voy:knob:range'],
  ['ARP', 2, 17, 'voy:knob:notes'],
  ['ARP', 2, 18, 'voy:knob:gate'],
  ['ARP', 2, 19, 'voy:knob:octave'],
  ['ARP', 2, 20, 'voy:knob:glide'],
  ['ARP', 2, 21, 'voy:knob:volume'],
  // ARP (setup 12), potards canal 2, page 2
  ['ARP', 2, 22, 'voy:knob:cutoff'],
  ['ARP', 2, 23, 'voy:knob:res'],
  ['ARP', 2, 24, 'voy:knob:envAmt'],
  ['ARP', 2, 25, 'voy:knob:fmode'],
  ['ARP', 2, 26, 'voy:knob:osc1'],
  ['ARP', 2, 27, 'voy:knob:osc2'],
  ['ARP', 2, 28, 'voy:knob:noise'],
  ['ARP', 2, 29, 'voy:knob:fm'],
  // ARP (setup 12), potards canal 2, page 3
  ['ARP', 2, 30, 'voy:knob:fA'],
  ['ARP', 2, 31, 'voy:knob:fD'],
  ['ARP', 2, 102, 'voy:knob:fS'],
  ['ARP', 2, 103, 'voy:knob:fR'],
  ['ARP', 2, 104, 'voy:knob:aA'],
  ['ARP', 2, 105, 'voy:knob:aD'],
  ['ARP', 2, 106, 'voy:knob:aS'],
  ['ARP', 2, 107, 'voy:knob:aR'],
  // ARP (setup 12), potards canal 2, page 4
  ['ARP', 2, 108, 'voy:knob:lfoRate'],
  ['ARP', 2, 109, 'voy:knob:lfoShape'],
  ['ARP', 2, 110, 'voy:knob:lfoDest'],
  ['ARP', 2, 111, 'voy:knob:lfoAmt'],
  ['ARP', 2, 112, 'voy:knob:dist'],
  ['ARP', 2, 113, 'voy:knob:chorus'],
  ['ARP', 2, 114, 'voy:knob:delay'],
  ['ARP', 2, 115, 'voy:knob:reverb'],
  // ARP (setup 12), boutons canal 10, page 1
  ['ARP', 10, 14, 'voy:running'],
  ['ARP', 10, 15, 'voy:random'],
  ['ARP', 10, 16, 'voy:clear'],
  ['ARP', 10, 17, 'voy:edit'],
  ['ARP', 10, 18, 'voy:open'],
  ['ARP', 10, 19, 'nav:machines'],
  ['ARP', 10, 20, 'nav:prev'],
  ['ARP', 10, 21, 'nav:next'],
  // ARP (setup 12), boutons canal 10, page 2
  ['ARP', 10, 22, 'voy:pad:0'],
  ['ARP', 10, 23, 'voy:pad:1'],
  ['ARP', 10, 24, 'voy:pad:2'],
  ['ARP', 10, 25, 'voy:pad:3'],
  ['ARP', 10, 26, 'voy:pad:4'],
  ['ARP', 10, 27, 'voy:pad:5'],
  ['ARP', 10, 28, 'voy:pad:6'],
  ['ARP', 10, 29, 'voy:pad:7'],
  // ARP (setup 12), boutons canal 10, page 3
  ['ARP', 10, 30, 'voy:knob:on1'],
  ['ARP', 10, 31, 'voy:knob:on2'],
  // BASS (setup 15), potards canal 5, page 1
  ['BASS', 5, 14, 'bass:knob:cutoff'],
  ['BASS', 5, 15, 'bass:knob:reso'],
  ['BASS', 5, 16, 'bass:knob:envmod'],
  ['BASS', 5, 17, 'bass:knob:decay'],
  ['BASS', 5, 18, 'bass:knob:accent'],
  ['BASS', 5, 19, 'bass:knob:drive'],
  ['BASS', 5, 20, 'bass:knob:sub'],
  ['BASS', 5, 21, 'bass:knob:volume'],
  // BASS (setup 15), potards canal 5, page 2
  ['BASS', 5, 22, 'bass:knob:wave'],
  ['BASS', 5, 23, 'bass:knob:glide'],
  ['BASS', 5, 24, 'bass:knob:octave'],
  ['BASS', 5, 25, 'bass:knob:style'],
  ['BASS', 5, 26, 'bass:knob:density'],
  ['BASS', 5, 27, 'bass:knob:slides'],
  ['BASS', 5, 28, 'bass:knob:accents'],
  ['BASS', 5, 29, 'bass:knob:range'],
  // BASS (setup 15), potards canal 5, page 3
  ['BASS', 5, 30, 'bass:knob:root'],
  ['BASS', 5, 31, 'bass:knob:scale'],
  ['BASS', 5, 102, 'rytm:enc:swing'],
  ['BASS', 5, 103, 'bass:knob:length'],
  ['BASS', 5, 104, 'bass:knob:accdecay'],
  ['BASS', 5, 105, 'bass:knob:sweep'],
  ['BASS', 5, 106, 'bass:knob:release'],
  ['BASS', 5, 107, 'bass:knob:tune'],
  // BASS (setup 15), boutons canal 13, page 1
  ['BASS', 13, 14, 'bass:running'],
  ['BASS', 13, 15, 'bass:key:gen'],
  ['BASS', 13, 16, 'bass:key:mutate'],
  ['BASS', 13, 17, 'bass:key:clear'],
  ['BASS', 13, 18, 'bass:key:accent'],
  ['BASS', 13, 19, 'bass:key:slide'],
  ['BASS', 13, 20, 'nav:prev'],
  ['BASS', 13, 21, 'nav:next'],
  // BASS (setup 15), boutons canal 13, page 2
  ['BASS', 13, 22, 'bass:trig:0'],
  ['BASS', 13, 23, 'bass:trig:1'],
  ['BASS', 13, 24, 'bass:trig:2'],
  ['BASS', 13, 25, 'bass:trig:3'],
  ['BASS', 13, 26, 'bass:trig:4'],
  ['BASS', 13, 27, 'bass:trig:5'],
  ['BASS', 13, 28, 'bass:trig:6'],
  ['BASS', 13, 29, 'bass:trig:7'],
  // BASS (setup 15), boutons canal 13, page 3
  ['BASS', 13, 30, 'bass:trig:8'],
  ['BASS', 13, 31, 'bass:trig:9'],
  ['BASS', 13, 102, 'bass:trig:10'],
  ['BASS', 13, 103, 'bass:trig:11'],
  ['BASS', 13, 104, 'bass:trig:12'],
  ['BASS', 13, 105, 'bass:trig:13'],
  ['BASS', 13, 106, 'bass:trig:14'],
  ['BASS', 13, 107, 'bass:trig:15'],
  // BASS (setup 15), boutons canal 13, page 4
  ['BASS', 13, 108, 'bass:key:notedn'],
  ['BASS', 13, 109, 'bass:key:noteup'],
  ['BASS', 13, 110, 'bass:key:octdn'],
  ['BASS', 13, 111, 'bass:key:octup'],
  ['BASS', 13, 112, 'bass:lock'],
  ['BASS', 13, 113, 'bass:key:edit'],
  ['BASS', 13, 114, 'nav:machines'],
  ['BASS', 13, 115, 'nav:all'],
  // DECK (setup 13), potards canal 3, page 1
  ['DECK', 3, 14, 'dj:dj-a-pitch'],
  ['DECK', 3, 15, 'dj:dj-ch4-fader'],
  ['DECK', 3, 16, 'dj:dj-ch4-gain'],
  ['DECK', 3, 17, 'dj:dj-ch4-hi'],
  ['DECK', 3, 18, 'dj:dj-ch4-mid'],
  ['DECK', 3, 19, 'dj:dj-ch4-low'],
  ['DECK', 3, 20, 'dj:dj-ch4-filter'],
  ['DECK', 3, 21, 'dj:dj-master'],
  // DECK (setup 13), potards canal 3, page 2
  ['DECK', 3, 22, 'dj:dj-b-pitch'],
  ['DECK', 3, 23, 'dj:dj-ch5-fader'],
  ['DECK', 3, 24, 'dj:dj-ch5-gain'],
  ['DECK', 3, 25, 'dj:dj-ch5-hi'],
  ['DECK', 3, 26, 'dj:dj-ch5-mid'],
  ['DECK', 3, 27, 'dj:dj-ch5-low'],
  ['DECK', 3, 28, 'dj:dj-ch5-filter'],
  ['DECK', 3, 29, 'dj:dj-master'],
  // DECK (setup 13), potards canal 3, page 3
  ['DECK', 3, 30, 'dj:dj-fx-overdrive'],
  ['DECK', 3, 31, 'dj:dj-fx-crush'],
  ['DECK', 3, 102, 'dj:dj-fx-chorus'],
  ['DECK', 3, 103, 'dj:dj-fx-flanger'],
  ['DECK', 3, 104, 'dj:dj-fx-trans'],
  ['DECK', 3, 105, 'dj:dj-fx-delay'],
  ['DECK', 3, 106, 'dj:dj-fx-reverb'],
  ['DECK', 3, 107, 'dj:dj-fxto'],
  // DECK (setup 13), potards canal 3, page 4
  ['DECK', 3, 108, 'dj:smpl:a:knob:level'],
  ['DECK', 3, 109, 'dj:smpl:a:knob:pitch'],
  ['DECK', 3, 110, 'dj:smpl:a:knob:filter'],
  ['DECK', 3, 111, 'dj:smpl:a:knob:position'],
  ['DECK', 3, 112, 'dj:smpl:b:knob:level'],
  ['DECK', 3, 113, 'dj:smpl:b:knob:pitch'],
  ['DECK', 3, 114, 'dj:smpl:b:knob:filter'],
  ['DECK', 3, 115, 'dj:smpl:b:knob:position'],
  // DECK (setup 13), boutons canal 11, page 1
  ['DECK', 11, 14, 'dj:dj-a-cue'],
  ['DECK', 11, 15, 'dj:dj-a-play'],
  ['DECK', 11, 16, 'dj:dj-a-sync'],
  ['DECK', 11, 17, 'dj:dj-a-smpl-open'],
  ['DECK', 11, 18, 'dj:dj-a-smpl-recdeck'],
  ['DECK', 11, 19, 'dj:dj-a-smpl-recmix'],
  ['DECK', 11, 20, 'dj:dj-a-smpl-play'],
  ['DECK', 11, 21, 'dj:dj-a-loop4'],
  // DECK (setup 13), boutons canal 11, page 2
  ['DECK', 11, 22, 'dj:dj-b-cue'],
  ['DECK', 11, 23, 'dj:dj-b-play'],
  ['DECK', 11, 24, 'dj:dj-b-sync'],
  ['DECK', 11, 25, 'dj:dj-b-smpl-open'],
  ['DECK', 11, 26, 'dj:dj-b-smpl-recdeck'],
  ['DECK', 11, 27, 'dj:dj-b-smpl-recmix'],
  ['DECK', 11, 28, 'dj:dj-b-smpl-play'],
  ['DECK', 11, 29, 'dj:dj-b-loop4'],
  // DECK (setup 13), boutons canal 11, page 3
  ['DECK', 11, 30, 'dj:dj-a-loop1'],
  ['DECK', 11, 31, 'dj:dj-a-loop2'],
  ['DECK', 11, 102, 'dj:dj-a-loop8'],
  ['DECK', 11, 103, 'dj:dj-a-bendm'],
  ['DECK', 11, 104, 'dj:dj-a-bendp'],
  ['DECK', 11, 105, 'dj:dj-a-tempom'],
  ['DECK', 11, 106, 'dj:dj-a-tempop'],
  ['DECK', 11, 107, 'dj:smpl:a:mode'],
  // DECK (setup 13), boutons canal 11, page 4
  ['DECK', 11, 108, 'dj:dj-b-loop1'],
  ['DECK', 11, 109, 'dj:dj-b-loop2'],
  ['DECK', 11, 110, 'dj:dj-b-loop8'],
  ['DECK', 11, 111, 'dj:dj-b-bendm'],
  ['DECK', 11, 112, 'dj:dj-b-bendp'],
  ['DECK', 11, 113, 'dj:dj-b-tempom'],
  ['DECK', 11, 114, 'dj:dj-b-tempop'],
  ['DECK', 11, 115, 'dj:smpl:b:mode'],
  // MIXER (setup 14), potards canal 4, page 1
  ['MIXER', 4, 14, 'dj:dj-ch1-fader'],
  ['MIXER', 4, 15, 'dj:dj-ch2-fader'],
  ['MIXER', 4, 16, 'dj:dj-ch3-fader'],
  ['MIXER', 4, 17, 'dj:dj-ch4-fader'],
  ['MIXER', 4, 18, 'dj:dj-ch5-fader'],
  ['MIXER', 4, 19, 'dj:dj-ch1-filter'],
  ['MIXER', 4, 20, 'dj:dj-ch4-filter'],
  ['MIXER', 4, 21, 'dj:dj-ch5-filter'],
  // MIXER (setup 14), potards canal 4, page 2
  ['MIXER', 4, 22, 'dj:dj-ch2-filter'],
  ['MIXER', 4, 23, 'dj:dj-ch3-filter'],
  ['MIXER', 4, 24, 'dj:dj-ch1-hi'],
  ['MIXER', 4, 25, 'dj:dj-ch1-low'],
  ['MIXER', 4, 26, 'dj:dj-ch2-hi'],
  ['MIXER', 4, 27, 'dj:dj-ch2-low'],
  ['MIXER', 4, 28, 'dj:dj-ch3-hi'],
  ['MIXER', 4, 29, 'dj:dj-ch3-low'],
  // MIXER (setup 14), potards canal 4, page 3
  ['MIXER', 4, 30, 'dj:dj-ch4-hi'],
  ['MIXER', 4, 31, 'dj:dj-ch4-mid'],
  ['MIXER', 4, 102, 'dj:dj-ch4-low'],
  ['MIXER', 4, 103, 'dj:dj-ch5-hi'],
  ['MIXER', 4, 104, 'dj:dj-ch5-mid'],
  ['MIXER', 4, 105, 'dj:dj-ch5-low'],
  ['MIXER', 4, 106, 'dj:dj-ch4-gain'],
  ['MIXER', 4, 107, 'dj:dj-ch5-gain'],
  // MIXER (setup 14), potards canal 4, page 4
  ['MIXER', 4, 108, 'dj:dj-fx-overdrive'],
  ['MIXER', 4, 109, 'dj:dj-fx-crush'],
  ['MIXER', 4, 110, 'dj:dj-fx-chorus'],
  ['MIXER', 4, 111, 'dj:dj-fx-flanger'],
  ['MIXER', 4, 112, 'dj:dj-fx-trans'],
  ['MIXER', 4, 113, 'dj:dj-fx-delay'],
  ['MIXER', 4, 114, 'dj:dj-fx-reverb'],
  ['MIXER', 4, 115, 'dj:dj-fxto'],
  // MIXER (setup 14), boutons canal 12, page 1
  ['MIXER', 12, 14, 'rytm:running'],
  ['MIXER', 12, 15, 'bass:running'],
  ['MIXER', 12, 16, 'voy:running'],
  ['MIXER', 12, 17, 'dj:dj-a-play'],
  ['MIXER', 12, 18, 'dj:dj-b-play'],
  ['MIXER', 12, 19, 'dj:dj-a-cue'],
  ['MIXER', 12, 20, 'dj:dj-b-cue'],
  ['MIXER', 12, 21, 'nav:machines'],
  // MIXER (setup 14), boutons canal 12, page 2
  ['MIXER', 12, 22, 'rytm:voice:BD:mute'],
  ['MIXER', 12, 23, 'rytm:voice:SD:mute'],
  ['MIXER', 12, 24, 'rytm:voice:CH:mute'],
  ['MIXER', 12, 25, 'rytm:voice:OH:mute'],
  ['MIXER', 12, 26, 'rytm:voice:CP:mute'],
  ['MIXER', 12, 27, 'rytm:voice:TOM:mute'],
  ['MIXER', 12, 28, 'rytm:voice:HT:mute'],
  ['MIXER', 12, 29, 'rytm:voice:CY:mute'],
  // MIXER (setup 14), boutons canal 12, page 3
  ['MIXER', 12, 30, 'dj:dj-a-sync'],
  ['MIXER', 12, 31, 'dj:dj-b-sync'],
  ['MIXER', 12, 102, 'dj:dj-a-loop4'],
  ['MIXER', 12, 103, 'dj:dj-b-loop4'],
  ['MIXER', 12, 104, 'dj:dj-adddeck'],
  ['MIXER', 12, 105, 'nav:prev'],
  ['MIXER', 12, 106, 'nav:next'],
  ['MIXER', 12, 107, 'nav:all'],
  // MIXER (setup 14), boutons canal 12, page 4
  ['MIXER', 12, 108, 'dj:dj-time1'],
  ['MIXER', 12, 109, 'dj:dj-time2'],
  ['MIXER', 12, 110, 'dj:dj-time3'],
  ['MIXER', 12, 111, 'dj:dj-time4'],
  ['MIXER', 12, 112, 'dj:dj-time5'],
  ['MIXER', 12, 113, 'dj:dj-time6'],
  // LIVE (setup 16), potards canal 6, page 1
  ['LIVE', 6, 14, 'dj:dj-ch1-fader'],
  ['LIVE', 6, 15, 'dj:dj-ch2-fader'],
  ['LIVE', 6, 16, 'dj:dj-ch3-fader'],
  ['LIVE', 6, 17, 'dj:dj-ch4-fader'],
  ['LIVE', 6, 18, 'dj:dj-ch5-fader'],
  ['LIVE', 6, 19, 'dj:dj-ch1-filter'],
  ['LIVE', 6, 20, 'dj:dj-ch4-filter'],
  ['LIVE', 6, 21, 'dj:dj-ch5-filter'],
  // LIVE (setup 16), potards canal 6, page 2
  ['LIVE', 6, 22, 'rytm:enc:swing'],
  ['LIVE', 6, 23, 'rytm:enc:stretch'],
  ['LIVE', 6, 24, 'rytm:enc:dist'],
  ['LIVE', 6, 25, 'rytm:enc:delay'],
  ['LIVE', 6, 26, 'rytm:enc:reverb'],
  ['LIVE', 6, 27, 'rytm:kit:tune'],
  ['LIVE', 6, 28, 'rytm:kit:decay'],
  ['LIVE', 6, 29, 'rytm:kit:drive'],
  // LIVE (setup 16), potards canal 6, page 3
  ['LIVE', 6, 30, 'voy:knob:cutoff'],
  ['LIVE', 6, 31, 'voy:knob:res'],
  ['LIVE', 6, 102, 'voy:knob:envAmt'],
  ['LIVE', 6, 103, 'voy:knob:fD'],
  ['LIVE', 6, 104, 'voy:knob:gate'],
  ['LIVE', 6, 105, 'voy:knob:rate'],
  ['LIVE', 6, 106, 'voy:knob:delay'],
  ['LIVE', 6, 107, 'voy:knob:reverb'],
  // LIVE (setup 16), potards canal 6, page 4
  ['LIVE', 6, 108, 'dj:dj-fx-overdrive'],
  ['LIVE', 6, 109, 'dj:dj-fx-crush'],
  ['LIVE', 6, 110, 'dj:dj-fx-chorus'],
  ['LIVE', 6, 111, 'dj:dj-fx-flanger'],
  ['LIVE', 6, 112, 'dj:dj-fx-trans'],
  ['LIVE', 6, 113, 'dj:dj-fx-delay'],
  ['LIVE', 6, 114, 'dj:dj-fx-reverb'],
  ['LIVE', 6, 115, 'dj:dj-fxto'],
  // LIVE (setup 16), boutons canal 14, page 1
  ['LIVE', 14, 14, 'rytm:running'],
  ['LIVE', 14, 15, 'bass:running'],
  ['LIVE', 14, 16, 'voy:running'],
  ['LIVE', 14, 17, 'dj:dj-a-play'],
  ['LIVE', 14, 18, 'dj:dj-b-play'],
  ['LIVE', 14, 19, 'dj:dj-a-cue'],
  ['LIVE', 14, 20, 'dj:dj-b-cue'],
  ['LIVE', 14, 21, 'nav:machines'],
  // LIVE (setup 16), boutons canal 14, page 2
  ['LIVE', 14, 22, 'rytm:voice:BD:mute'],
  ['LIVE', 14, 23, 'rytm:voice:SD:mute'],
  ['LIVE', 14, 24, 'rytm:voice:CH:mute'],
  ['LIVE', 14, 25, 'rytm:voice:OH:mute'],
  ['LIVE', 14, 26, 'rytm:voice:CP:mute'],
  ['LIVE', 14, 27, 'rytm:voice:TOM:mute'],
  ['LIVE', 14, 28, 'rytm:voice:HT:mute'],
  ['LIVE', 14, 29, 'rytm:voice:CY:mute'],
  // LIVE (setup 16), boutons canal 14, page 3
  ['LIVE', 14, 30, 'voy:pad:0'],
  ['LIVE', 14, 31, 'voy:pad:1'],
  ['LIVE', 14, 102, 'voy:pad:2'],
  ['LIVE', 14, 103, 'voy:pad:3'],
  ['LIVE', 14, 104, 'voy:pad:4'],
  ['LIVE', 14, 105, 'voy:pad:5'],
  ['LIVE', 14, 106, 'voy:pad:6'],
  ['LIVE', 14, 107, 'voy:pad:7'],
  // LIVE (setup 16), boutons canal 14, page 4
  ['LIVE', 14, 108, 'dj:dj-time1'],
  ['LIVE', 14, 109, 'dj:dj-time2'],
  ['LIVE', 14, 110, 'dj:dj-time4'],
  ['LIVE', 14, 111, 'dj:dj-time5'],
  ['LIVE', 14, 112, 'dj:dj-a-smpl-play'],
  ['LIVE', 14, 113, 'dj:dj-b-smpl-play'],
  ['LIVE', 14, 114, 'nav:prev'],
  ['LIVE', 14, 115, 'nav:next'],
  // Les nouvelles adresses : a la suite, jamais au milieu
  // 2026-10-09 : les sequenceurs (midi/seqlink.ts), sur des canaux libres (7, 8, 15, 16) : la place sur la page donne le CC
  // RSEQ (setup 17), potards canal 7, page 1 : les encodeurs de page
  ['RSEQ', 7, 14, 'rytm:knob:1'],
  ['RSEQ', 7, 15, 'rytm:knob:2'],
  ['RSEQ', 7, 16, 'rytm:knob:3'],
  ['RSEQ', 7, 17, 'rytm:knob:4'],
  ['RSEQ', 7, 18, 'rytm:knob:5'],
  ['RSEQ', 7, 19, 'rytm:knob:6'],
  ['RSEQ', 7, 20, 'rytm:knob:7'],
  ['RSEQ', 7, 21, 'rytm:knob:8'],
  // RSEQ (setup 17), potards canal 7, page 2 : les memes encodeurs (la meme cible deux fois : deux lignes)
  ['RSEQ', 7, 22, 'rytm:knob:1'],
  ['RSEQ', 7, 23, 'rytm:knob:2'],
  ['RSEQ', 7, 24, 'rytm:knob:3'],
  ['RSEQ', 7, 25, 'rytm:knob:4'],
  ['RSEQ', 7, 26, 'rytm:knob:5'],
  ['RSEQ', 7, 27, 'rytm:knob:6'],
  ['RSEQ', 7, 28, 'rytm:knob:7'],
  ['RSEQ', 7, 29, 'rytm:knob:8'],
  // RSEQ (setup 17), potards canal 7, page 3 : les volumes des voix
  ['RSEQ', 7, 30, 'rytm:voice:BD:level'],
  ['RSEQ', 7, 31, 'rytm:voice:SD:level'],
  ['RSEQ', 7, 102, 'rytm:voice:CH:level'],
  ['RSEQ', 7, 103, 'rytm:voice:OH:level'],
  ['RSEQ', 7, 104, 'rytm:voice:CP:level'],
  ['RSEQ', 7, 105, 'rytm:voice:TOM:level'],
  ['RSEQ', 7, 106, 'rytm:voice:HT:level'],
  ['RSEQ', 7, 107, 'rytm:voice:CY:level'],
  // RSEQ (setup 17), potards canal 7, page 4 : la machine
  ['RSEQ', 7, 108, 'rytm:enc:level'],
  ['RSEQ', 7, 109, 'rytm:enc:tempo'],
  ['RSEQ', 7, 110, 'rytm:enc:swing'],
  ['RSEQ', 7, 111, 'rytm:enc:stretch'],
  ['RSEQ', 7, 112, 'rytm:enc:dist'],
  ['RSEQ', 7, 113, 'rytm:enc:chorus'],
  ['RSEQ', 7, 114, 'rytm:enc:delay'],
  ['RSEQ', 7, 115, 'rytm:enc:reverb'],
  // RSEQ (setup 17), boutons canal 15, page 1 : les huit pas de la fenetre
  ['RSEQ', 15, 14, 'rytm:seq:1'],
  ['RSEQ', 15, 15, 'rytm:seq:2'],
  ['RSEQ', 15, 16, 'rytm:seq:3'],
  ['RSEQ', 15, 17, 'rytm:seq:4'],
  ['RSEQ', 15, 18, 'rytm:seq:5'],
  ['RSEQ', 15, 19, 'rytm:seq:6'],
  ['RSEQ', 15, 20, 'rytm:seq:7'],
  ['RSEQ', 15, 21, 'rytm:seq:8'],
  // RSEQ (setup 17), boutons canal 15, page 2 : les pages, la fenetre, FOLLOW
  ['RSEQ', 15, 22, 'rytm:page:trig'],
  ['RSEQ', 15, 23, 'rytm:page:src'],
  ['RSEQ', 15, 24, 'rytm:page:smpl'],
  ['RSEQ', 15, 25, 'rytm:page:fltr'],
  ['RSEQ', 15, 26, 'rytm:page:amp'],
  ['RSEQ', 15, 27, 'rytm:page:fx'],
  ['RSEQ', 15, 28, 'rytm:seq:window'],
  ['RSEQ', 15, 29, 'rytm:seq:follow'],
  // RSEQ (setup 17), boutons canal 15, page 3 : la voix des pas
  ['RSEQ', 15, 30, 'rytm:seq:voice:BD'],
  ['RSEQ', 15, 31, 'rytm:seq:voice:SD'],
  ['RSEQ', 15, 102, 'rytm:seq:voice:CH'],
  ['RSEQ', 15, 103, 'rytm:seq:voice:OH'],
  ['RSEQ', 15, 104, 'rytm:seq:voice:CP'],
  ['RSEQ', 15, 105, 'rytm:seq:voice:TOM'],
  ['RSEQ', 15, 106, 'rytm:seq:voice:HT'],
  ['RSEQ', 15, 107, 'rytm:seq:voice:CY'],
  // RSEQ (setup 17), boutons canal 15, page 4 : jouer
  ['RSEQ', 15, 108, 'rytm:running'],
  ['RSEQ', 15, 109, 'rytm:clear'],
  ['RSEQ', 15, 110, 'rytm:random'],
  ['RSEQ', 15, 111, 'rytm:lock'],
  ['RSEQ', 15, 112, 'rytm:edit'],
  ['RSEQ', 15, 113, 'nav:prev'],
  ['RSEQ', 15, 114, 'nav:next'],
  ['RSEQ', 15, 115, 'nav:machines'],
  // BSEQ (setup 18), potards canal 8, page 1 : les encodeurs de page
  ['BSEQ', 8, 14, 'bass:knob:1'],
  ['BSEQ', 8, 15, 'bass:knob:2'],
  ['BSEQ', 8, 16, 'bass:knob:3'],
  ['BSEQ', 8, 17, 'bass:knob:4'],
  ['BSEQ', 8, 18, 'bass:knob:5'],
  ['BSEQ', 8, 19, 'bass:knob:6'],
  ['BSEQ', 8, 20, 'bass:knob:7'],
  ['BSEQ', 8, 21, 'bass:knob:8'],
  // BSEQ (setup 18), potards canal 8, page 2 : les memes encodeurs
  ['BSEQ', 8, 22, 'bass:knob:1'],
  ['BSEQ', 8, 23, 'bass:knob:2'],
  ['BSEQ', 8, 24, 'bass:knob:3'],
  ['BSEQ', 8, 25, 'bass:knob:4'],
  ['BSEQ', 8, 26, 'bass:knob:5'],
  ['BSEQ', 8, 27, 'bass:knob:6'],
  ['BSEQ', 8, 28, 'bass:knob:7'],
  ['BSEQ', 8, 29, 'bass:knob:8'],
  // BSEQ (setup 18), potards canal 8, page 3 : le generateur et la gamme
  ['BSEQ', 8, 30, 'bass:knob:style'],
  ['BSEQ', 8, 31, 'bass:knob:density'],
  ['BSEQ', 8, 102, 'bass:knob:slides'],
  ['BSEQ', 8, 103, 'bass:knob:accents'],
  ['BSEQ', 8, 104, 'bass:knob:range'],
  ['BSEQ', 8, 105, 'bass:knob:root'],
  ['BSEQ', 8, 106, 'bass:knob:scale'],
  ['BSEQ', 8, 107, 'bass:knob:octave'],
  // BSEQ (setup 18), potards canal 8, page 4 : le tempo, le groove, la 303
  ['BSEQ', 8, 108, 'rytm:enc:tempo'],
  ['BSEQ', 8, 109, 'rytm:enc:swing'],
  ['BSEQ', 8, 110, 'bass:knob:cutoff'],
  ['BSEQ', 8, 111, 'bass:knob:reso'],
  ['BSEQ', 8, 112, 'bass:knob:envmod'],
  ['BSEQ', 8, 113, 'bass:knob:decay'],
  ['BSEQ', 8, 114, 'bass:knob:accent'],
  ['BSEQ', 8, 115, 'bass:knob:volume'],
  // BSEQ (setup 18), boutons canal 16, page 1 : les huit pas de la fenetre
  ['BSEQ', 16, 14, 'bass:seq:1'],
  ['BSEQ', 16, 15, 'bass:seq:2'],
  ['BSEQ', 16, 16, 'bass:seq:3'],
  ['BSEQ', 16, 17, 'bass:seq:4'],
  ['BSEQ', 16, 18, 'bass:seq:5'],
  ['BSEQ', 16, 19, 'bass:seq:6'],
  ['BSEQ', 16, 20, 'bass:seq:7'],
  ['BSEQ', 16, 21, 'bass:seq:8'],
  // BSEQ (setup 18), boutons canal 16, page 2 : les pages, ACCENT, SLIDE, la fenetre, FOLLOW
  ['BSEQ', 16, 22, 'bass:page:voice'],
  ['BSEQ', 16, 23, 'bass:page:filter'],
  ['BSEQ', 16, 24, 'bass:page:env'],
  ['BSEQ', 16, 25, 'bass:page:fx'],
  ['BSEQ', 16, 26, 'bass:key:accent'],
  ['BSEQ', 16, 27, 'bass:key:slide'],
  ['BSEQ', 16, 28, 'bass:seq:window'],
  ['BSEQ', 16, 29, 'bass:seq:follow'],
  // BSEQ (setup 18), boutons canal 16, page 3 : la note du pas, la liaison, MUTATE
  ['BSEQ', 16, 30, 'bass:key:notedn'],
  ['BSEQ', 16, 31, 'bass:key:noteup'],
  ['BSEQ', 16, 102, 'bass:key:octdn'],
  ['BSEQ', 16, 103, 'bass:key:octup'],
  ['BSEQ', 16, 104, 'bass:seq:tie'],
  ['BSEQ', 16, 105, 'bass:key:mutate'],
  // BSEQ (setup 18), boutons canal 16, page 4 : jouer
  ['BSEQ', 16, 108, 'bass:running'],
  ['BSEQ', 16, 109, 'bass:key:clear'],
  ['BSEQ', 16, 110, 'bass:key:gen'],
  ['BSEQ', 16, 111, 'bass:lock'],
  ['BSEQ', 16, 112, 'bass:key:edit'],
  ['BSEQ', 16, 113, 'nav:prev'],
  ['BSEQ', 16, 114, 'nav:next'],
  ['BSEQ', 16, 115, 'nav:machines'],
  // 2026-10-09 (la revue) : BSEQ page 3, ACCENT et SLIDE une deuxieme fois (le pas choisi se regle sur une seule page)
  ['BSEQ', 16, 106, 'bass:key:accent'],
  ['BSEQ', 16, 107, 'bass:key:slide'],
  // 2026-10-09 (MM-RYTM etape 2) : RSEQ page 2, les pages VOICE et ENV (TRIG SRC SMPL AMP gardent leurs adresses, des
  // alias de VOICE et ENV), MUTE et SOLO pour garder la rangee de huit
  ['RSEQ', 15, 3, 'rytm:page:voice'],
  ['RSEQ', 15, 9, 'rytm:page:env'],
  ['RSEQ', 15, 85, 'rytm:mute'],
  ['RSEQ', 15, 86, 'rytm:solo'],
  // 2026-10-09 (le moteur MONARK) : BASS (setup 15), potards canal 5, page 4 : le melangeur et le contour du Minimoog
  ['BASS', 5, 108, 'bass:knob:o2lvl'],
  ['BASS', 5, 109, 'bass:knob:o3lvl'],
  ['BASS', 5, 110, 'bass:knob:o2fine'],
  ['BASS', 5, 111, 'bass:knob:noise'],
  ['BASS', 5, 112, 'bass:knob:feedback'],
  ['BASS', 5, 113, 'bass:knob:fattack'],
  ['BASS', 5, 114, 'bass:knob:fsustain'],
  ['BASS', 5, 115, 'bass:knob:fmode'],
  // 2026-10-09 (le generateur du MM-BASS) : GEN et MUTATE tenus (tape : la suivante, muter ; 500 ms : la prise d'avant,
  // annuler), BASS page 1, BSEQ page 3 (MUTATE) et 4 (GEN) ; les adresses d'avant restent a bass:key:gen et bass:key:mutate
  ['BASS', 13, 3, 'bass:gen'],
  ['BASS', 13, 9, 'bass:mutate'],
  ['BSEQ', 16, 3, 'bass:mutate'],
  ['BSEQ', 16, 9, 'bass:gen'],
  // 2026-10-10 : BIT et COMP sur la page 1 du RYTM ; sans le MM-BASS cache, MID et GAIN du RYTM et de l'ARP sur la page 2
  // du MIXER, le filtre de l'ARP et MM-STUDIO a la place de la voie et du RUN du MM-BASS (MIXER, LIVE)
  ['RYTM', 1, 3, 'rytm:enc:bits'],
  ['RYTM', 1, 9, 'rytm:enc:comp'],
  ['MIXER', 4, 3, 'dj:dj-ch1-mid'],
  ['MIXER', 4, 9, 'dj:dj-ch1-gain'],
  ['MIXER', 4, 85, 'dj:dj-ch3-mid'],
  ['MIXER', 4, 86, 'dj:dj-ch3-gain'],
  ['MIXER', 12, 114, 'nav:all'],
  ['LIVE', 6, 3, 'dj:dj-ch3-filter'],
  ['LIVE', 14, 3, 'nav:all'],
];
